[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
safe_harbour = "CxQZFj98gyJSJhBh4kZ6jCpQcaW1gcx9gcwcCr2KrkNH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/0x4ka5h/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
