[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.localnet]
safe_harbour = "8wRWiR6DFVP3JmW8i4bTa393PorrTXsQhrZgdfQjLpmX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/0x4ka5h/.config/solana/id.json"

[scripts]
test = "npx --yes ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
