[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
resolution = true
skip-lint = false

[programs.devnet]
safe_harbor = "6Q1MaYkpJCo7Kyz6dwFkN5rypTpVsmZSzqXvwtfrU1Ty"

[programs.localnet]
safe_harbor = "6Q1MaYkpJCo7Kyz6dwFkN5rypTpVsmZSzqXvwtfrU1Ty"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"
